<?php

/**
 * ACF Fields: Ranking Settings.
 *
 * @package Edumed
 */

if (! defined('ABSPATH')) {
  exit; // Prevent direct access.
}

if (function_exists('acf_add_local_field_group')) {
  acf_add_local_field_group(array(
    'key' => 'group_ranking_settings',
    'title' => 'Ranking Setting',
    'fields' => array(
      array(
        'key' => 'field_ranking_post_type',
        'label' => 'Post type',
        'name' => 'post_type',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'choices' => array(
          'school_ranking' => 'School Ranking',
          'feature_ranking' => 'Feature Ranking',
        ),
        'default_value' => 'school_ranking',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
        'allow_null' => 0,
        'allow_in_bindings' => 1,
        'ui' => 0,
        'ajax' => 0,
      ),
      array(
        'key' => 'field_ranking_block_design',
        'label' => 'Block Design',
        'name' => 'block_design',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'choices' => array(
          'school_ranking' => 'School Ranking',
          'ranking_2026' => 'Rankings 2026',
          'feature_ranking' => 'Feature Ranking',
        ),
        'default_value' => 'school_ranking',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_custom' => 0,
        'placeholder' => '',
        'search_placeholder' => '',
        'allow_null' => 0,
        'allow_in_bindings' => 1,
        'ui' => 0,
        'ajax' => 0,
      ),
      array(
        'key' => 'field_ranking_program',
        'label' => 'Program',
        'name' => 'program',
        'aria-label' => '',
        'type' => 'taxonomy',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'taxonomy' => 'school_ranking_category',
        'add_term' => 0,
        'save_terms' => 1,
        'load_terms' => 1,
        'return_format' => 'object',
        'field_type' => 'select',
      ),
      array(
        'key' => 'field_ranking_default_open',
        'label' => 'Default Open',
        'name' => 'default_open',
        'aria-label' => '',
        'type' => 'range',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'default_value' => 3,
        'min' => '1',
        'max' => '10',
      ),
      array(
        'key' => 'field_ranking_metodology_text',
        'label' => 'Metodology Text',
        'name' => 'metodology_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_ranking_has_2_and_4_years',
        'label' => 'Has 2 and 4 Years?',
        'name' => 'has_2_and_4_years',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.33',
        ),
        'choices' => array(
          'yes' => 'Yes',
          'no' => 'No',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 1,
      ),
      array(
        'key' => 'field_ranking_default_level_year',
        'label' => 'Default Level Year',
        'name' => 'default_level_year',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
        ),
        'choices' => array(
          'four-year' => '4-year',
          'two-year' => '2-year',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 1,
      ),
      array(
        'key' => 'field_ranking_version',
        'label' => 'Version',
        'name' => 'version',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
        ),
        'choices' => array(
          2026 => '2026',
          2025 => '2025',
          2024 => '2024',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'placeholder' => '',
        'allow_null' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));
}
